source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gemcutter.org"
source "http://gems.github.com"

gem "will_paginate"
gem "authlogic"
gem "searchlogic"
gem "mysql"
gem "capistrano"
